task_label: pour
demo_tool_label: mug
test_tool_label: teapot
demo_target_label: bowl
test_target_label: bowl

params:
  iou_thresh: 0.1
  bbox_expansion: 0.05
  num_candidate_keypoints: 12
  vp_flag: true
  sd_dino_flag: true

owlv2:
  box_threshold: 0.10
  text_threshold: 0.10
  conf_threshold: 0.05

paths:
  base_data_path: \home\oguz\Desktop\attempt_three\attempt_three